baseurl: /

name: Zheng I'm
author: Zheng Yan
license: <a href="http://creativecommons.org/licenses/by/4.0/">CC-BY</a>
description: Pull myself up by my own bootstraps.
url: http://blog.zheng.im

markdown: kramdown
kramdown:
  input: GFM
  footnote_backlink: '&#8617;&#65038;'
